packages:
  - 'config/*'
  - 'packages/*'
  - 'tsed/*'

catalog:
  '@swc/core': 1.15.11
  '@swc/helpers': 0.5.18
  '@types/node': 25.2.3
  '@types/supertest': 6.0.3
  '@vitest/coverage-v8': 4.0.18
  eslint: 10.0.2
  mongoose: 9.2.1
  supertest: 7.2.2
  tslib: 2.8.1
  tsup: 8.5.1
  typescript: 5.9.3
  vitest: 4.0.18

catalogs:
  tsed:
    ajv: 8.17.1
    '@tsed/ajv': 8.25.1
    '@tsed/common': 8.25.1
    '@tsed/core': 8.25.1
    '@tsed/di': 8.25.1
    '@tsed/json-mapper': 8.25.1
    '@tsed/logger': 8.0.4
    '@tsed/mongoose': 8.25.1
    '@tsed/openspec': 8.25.1
    '@tsed/platform-express': 8.25.1
    '@tsed/platform-http': 8.25.1
    '@tsed/platform-params': 8.25.1
    '@tsed/platform-views': 8.25.1
    '@tsed/schema': 8.25.1
    '@tsed/swagger': 8.25.1
    '@tsed/testcontainers-mongo': 8.25.1