packages:
  - 'config/*'
  - 'packages/*'
  - 'tsed/*'

catalog:
  '@swc/core': ^1.10.18
  '@swc/helpers': ^0.5.15
  '@types/node': ^22.13.4
  '@types/supertest': ^6.0.2
  '@vitest/coverage-v8': ^3.0.6
  eslint: ^9.20.1
  mongoose: ^8.10.1
  supertest: ^7.0.0
  tslib: ^2.8.1
  tsup: ^8.3.6
  typescript: ^5.7.3
  typescript-eslint: ^8.24.1
  vitest: ^3.0.6

catalogs:
  tsed:
    ajv: ^8.17.1
    '@tsed/ajv': ^8.5.0
    '@tsed/common': ^8.5.0
    '@tsed/core': ^8.5.0
    '@tsed/di': ^8.5.0
    '@tsed/json-mapper': ^8.5.0
    '@tsed/logger': ^7.0.1
    '@tsed/mongoose': ^8.5.0
    '@tsed/openspec': ^8.5.0
    '@tsed/platform-express': ^8.5.0
    '@tsed/platform-http': ^8.5.0
    '@tsed/platform-params': ^8.5.0
    '@tsed/platform-views': ^8.5.0
    '@tsed/schema': ^8.5.0
    '@tsed/swagger': ^8.5.0
    '@tsed/testcontainers-mongo': ^8.5.0