packages:
  - 'config/*'
  - 'packages/*'
  - 'tsed/*'

catalog:
  '@swc/core': ^1.10.18
  '@swc/helpers': ^0.5.15
  '@types/node': ^22.13.4
  '@types/supertest': ^6.0.2
  '@vitest/coverage-v8': ^3.0.6
  eslint: ^9.20.1
  mongoose: ^8.10.1
  supertest: ^7.0.0
  tslib: ^2.8.1
  tsup: ^8.3.6
  typescript: ^5.7.3
  typescript-eslint: ^8.24.1
  vitest: ^3.0.6

catalogs:
  tsed:
    ajv: 8.17.1
    '@tsed/ajv': 8.19.4
    '@tsed/common': 8.19.4
    '@tsed/core': 8.19.4
    '@tsed/di': 8.19.4
    '@tsed/json-mapper': 8.19.4
    '@tsed/logger': 8.0.4
    '@tsed/mongoose': 8.19.4
    '@tsed/openspec': 8.19.4
    '@tsed/platform-express': 8.19.4
    '@tsed/platform-http': 8.19.4
    '@tsed/platform-params': 8.19.4
    '@tsed/platform-views': 8.19.4
    '@tsed/schema': 8.19.4
    '@tsed/swagger': 8.19.4
    '@tsed/testcontainers-mongo': 8.19.4