packages:
  - 'config/*'

catalog:
  '@swc/core': ^1.10.0
  '@swc/jest': ^0.2.37
  '@types/jest': ^29.5.14
  eslint: ^9.16.0
  jest: ^29.7.0
  tslib: ^2.8.1
  tsup: ^8.3.5
  typescript: ^5.7.2
  typescript-eslint: ^8.17.0