packages:
  - 'config/*'
  - 'packages/*'
  - 'tsed/*'

catalog:
  '@swc/core': ^1.10.0
  '@swc/helpers': ^0.5.15
  '@vitest/coverage-v8': ^2.1.8
  eslint: ^9.16.0
  tslib: ^2.8.1
  tsup: ^8.3.5
  typescript: ^5.7.2
  typescript-eslint: ^8.17.0
  vitest: ^2.1.8

catalogs:
  tsed:
    '@tsed/ajv': ^8.4.6
    '@tsed/common': ^8.4.6
    '@tsed/core': ^8.4.6
    '@tsed/di': ^8.4.6
    '@tsed/json-mapper': ^8.4.6
    '@tsed/logger': ^7.0.1
    '@tsed/platform-express': ^8.4.6
    '@tsed/platform-http': ^8.4.6
    '@tsed/schema': ^8.4.6