import { MongoosePlainObject } from './MongoosePlainObject.js';

/**
 * Type utility for creating Mongoose documents with auto-managed fields excluded.
 * 
 * This type prepares objects for Mongoose `create()` operations by:
 * - Converting Mongoose documents to plain objects (removing methods)
 * - Making all properties optional (Partial) for flexible object creation
 * - Excluding auto-managed fields that Mongoose handles automatically:
 *   - `id` and `_id` (generated by MongoDB)
 *   - `createdAt` and `updatedAt` (managed by timestamps)
 * 
 * Use this type when defining the structure for new document creation,
 * ensuring that only user-provided data is included while preventing
 * accidental assignment of system-managed fields.
 * 
 * @typeParam T - The Mongoose document type to prepare for creation
 * 
 * @example
 * ```typescript
 * import { Document } from 'mongoose';
 * 
 * interface UserDocument extends Document {
 *   _id: ObjectId;
 *   name: string;
 *   email: string;
 *   role?: string;
 *   createdAt: Date;
 *   updatedAt: Date;
 * }
 * 
 * // Type for creating new users
 * type UserCreateData = MongoosePlainObjectCreate<UserDocument>;
 * // Result: Partial<{ name: string, email: string, role?: string }>
 * 
 * const newUser: UserCreateData = {
 *   name: 'John Doe',
 *   email: 'john@example.com'
 *   // _id, createdAt, updatedAt are excluded
 *   // role is optional
 * };
 * ```
 * 
 * @example
 * ```typescript
 * // Use in mapper modelToMongoCreateObject method
 * class UserMapper extends MongoMapper<UserDocument, UserModel> {
 *   async modelToMongoCreateObject(model: UserModel): Promise<MongoosePlainObjectCreate<UserDocument>> {
 *     return {
 *       name: model.name,
 *       email: model.email,
 *       role: model.role
 *       // No need to handle _id, createdAt, updatedAt
 *     };
 *   }
 * }
 * ```
 */
export type MongoosePlainObjectCreate<T> = Omit<Partial<MongoosePlainObject<T>>, 'id' | '_id' | 'createdAt' | 'updatedAt'>;
