import { ObjectID } from '@tsed/mongoose';
import { Format } from '@tsed/schema';

/**
 * Base model class for Mongoose models in Ts.ED applications.
 * 
 * Provides standard MongoDB fields that should be present in all document models:
 * - `_id`: MongoDB ObjectID (exposed as `id` in JSON)
 * - `createdAt`: Document creation timestamp
 * - `updatedAt`: Document last update timestamp
 * 
 * All Mongoose models in the application should extend this base class to ensure
 * consistent field structure and automatic timestamp management.
 * 
 * @remarks
 * - The `_id` field is mapped to `id` in JSON responses via @ObjectID decorator
 * - Timestamp fields are automatically managed by Mongoose when `timestamps: true` is set in schema options
 * - All fields are formatted according to @tsed/schema decorators for OpenAPI documentation
 * - This class should be used with @Model decorator from @tsed/mongoose
 * 
 * @example
 * ```typescript
 * import { Model, ObjectID } from '@tsed/mongoose';
 * import { Property, Required } from '@tsed/schema';
 * import { BaseMongo } from './BaseMongo';
 * 
 * @Model({
 *   collection: 'users',
 *   schemaOptions: {
 *     timestamps: true  // Enables automatic createdAt/updatedAt management
 *   }
 * })
 * export class User extends BaseMongo {
 *   @Required()
 *   @Property()
 *   name: string;
 * 
 *   @Property()
 *   email: string;
 * }
 * ```
 * 
 * @example
 * ```typescript
 * // When serialized to JSON, _id becomes id
 * const user = await userModel.findById(id);
 * // Response: { id: '...', name: 'John', email: '...', createdAt: '...', updatedAt: '...' }
 * ```
 * 
 * @see {@link https://tsed.io/tutorials/mongoose.html Ts.ED Mongoose Documentation}
 */
export class BaseMongo {
    /**
     * MongoDB document identifier.
     * 
     * Automatically generated by MongoDB when creating a new document.
     * Mapped to `id` field in JSON responses.
     * 
     * @type {ObjectID}
     */
    @ObjectID('id')
    public _id: ObjectID;

    /**
     * Document creation timestamp.
     * 
     * Automatically set by Mongoose when the document is first created
     * (requires `timestamps: true` in schema options).
     * 
     * @type {Date}
     * @format date-time
     */
    @Format('date-time')
    public createdAt: Date;

    /**
     * Document last update timestamp.
     * 
     * Automatically updated by Mongoose whenever the document is modified
     * (requires `timestamps: true` in schema options).
     * 
     * @type {Date}
     * @format date-time
     */
    @Format('date-time')
    public updatedAt: Date;
}

