name: Release packages to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://npm.pkg.github.com/
          scope: '@radoslavirha'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Create Release Pull Request and Publish to GitHub Packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Install Octokit
      #   run: pnpm add --global @octokit/rest
      # - name: Create Release Pull Request
      #   run: pnpm changeset version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Publish to npm
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: pnpm changeset publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Create GitHub Releases
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: |
      #     pnpm changeset status --output json > changeset-status.json
      #     node .github/scripts/create-releases.js
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}